# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(760, 645)
        MainWindow.setStyleSheet(u"#centralwidget {\n"
"    }")
        self.actionPassword_Manager = QAction(MainWindow)
        self.actionPassword_Manager.setObjectName(u"actionPassword_Manager")
        self.actionPassword_Generator = QAction(MainWindow)
        self.actionPassword_Generator.setObjectName(u"actionPassword_Generator")
        self.actionUser_Name_Generator = QAction(MainWindow)
        self.actionUser_Name_Generator.setObjectName(u"actionUser_Name_Generator")
        self.import_action = QAction(MainWindow)
        self.import_action.setObjectName(u"import_action")
        self.export_action = QAction(MainWindow)
        self.export_action.setObjectName(u"export_action")
        self.credits_action = QAction(MainWindow)
        self.credits_action.setObjectName(u"credits_action")
        self.help_page_action = QAction(MainWindow)
        self.help_page_action.setObjectName(u"help_page_action")
        self.central_widget = QWidget(MainWindow)
        self.central_widget.setObjectName(u"central_widget")
        self.header_1_label = QLabel(self.central_widget)
        self.header_1_label.setObjectName(u"header_1_label")
        self.header_1_label.setGeometry(QRect(10, 10, 740, 30))
        font = QFont()
        font.setFamily(u"Manjari")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QFont.PreferDefault)
        self.header_1_label.setFont(font)
        self.header_1_label.setStyleSheet(u"#header_1_label {\n"
"    background: #64ccff;\n"
"    padding-left: 50px;\n"
"	border-radius: 5px;\n"
"	color: white;\n"
" }")
        self.header_1_label.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.header_1_label.setIndent(0)
        self.list_of_passwords_list_view = QListView(self.central_widget)
        self.list_of_passwords_list_view.setObjectName(u"list_of_passwords_list_view")
        self.list_of_passwords_list_view.setGeometry(QRect(10, 50, 250, 560))
        self.cao_group_box = QGroupBox(self.central_widget)
        self.cao_group_box.setObjectName(u"cao_group_box")
        self.cao_group_box.setGeometry(QRect(270, 340, 480, 270))
        self.cao_cancel_button = QPushButton(self.cao_group_box)
        self.cao_cancel_button.setObjectName(u"cao_cancel_button")
        self.cao_cancel_button.setGeometry(QRect(20, 230, 100, 25))
        self.cao_password_line_edit = QLineEdit(self.cao_group_box)
        self.cao_password_line_edit.setObjectName(u"cao_password_line_edit")
        self.cao_password_line_edit.setGeometry(QRect(155, 130, 270, 25))
        self.cao_password_line_edit.setMaxLength(100)
        self.cao_add_button = QPushButton(self.cao_group_box)
        self.cao_add_button.setObjectName(u"cao_add_button")
        self.cao_add_button.setGeometry(QRect(170, 230, 100, 25))
        self.cao_object_name_label = QLabel(self.cao_group_box)
        self.cao_object_name_label.setObjectName(u"cao_object_name_label")
        self.cao_object_name_label.setGeometry(QRect(20, 50, 100, 25))
        self.cao_object_name_line_edit = QLineEdit(self.cao_group_box)
        self.cao_object_name_line_edit.setObjectName(u"cao_object_name_line_edit")
        self.cao_object_name_line_edit.setGeometry(QRect(155, 50, 270, 25))
        self.cao_object_name_line_edit.setMaxLength(100)
        self.cao_username_label = QLabel(self.cao_group_box)
        self.cao_username_label.setObjectName(u"cao_username_label")
        self.cao_username_label.setGeometry(QRect(20, 90, 100, 25))
        self.cao_url_label = QLabel(self.cao_group_box)
        self.cao_url_label.setObjectName(u"cao_url_label")
        self.cao_url_label.setGeometry(QRect(20, 170, 100, 25))
        self.cao_username_line_edit = QLineEdit(self.cao_group_box)
        self.cao_username_line_edit.setObjectName(u"cao_username_line_edit")
        self.cao_username_line_edit.setGeometry(QRect(155, 90, 270, 25))
        self.cao_username_line_edit.setMaxLength(100)
        self.cao_password_label = QLabel(self.cao_group_box)
        self.cao_password_label.setObjectName(u"cao_password_label")
        self.cao_password_label.setGeometry(QRect(20, 130, 100, 25))
        self.cao_url_line_edit = QLineEdit(self.cao_group_box)
        self.cao_url_line_edit.setObjectName(u"cao_url_line_edit")
        self.cao_url_line_edit.setGeometry(QRect(155, 170, 270, 25))
        self.cao_url_line_edit.setMaxLength(1500)
        self.cao_generate_password_button = QPushButton(self.cao_group_box)
        self.cao_generate_password_button.setObjectName(u"cao_generate_password_button")
        self.cao_generate_password_button.setGeometry(QRect(435, 130, 25, 25))
        self.cao_generate_password_button.setStyleSheet(u"#createDataRPGBtn {\n"
"	border: none;\n"
"}")
        icon = QIcon()
        icon.addFile(u":/icons/generator_img.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cao_generate_password_button.setIcon(icon)
        self.cao_generate_username_button = QPushButton(self.cao_group_box)
        self.cao_generate_username_button.setObjectName(u"cao_generate_username_button")
        self.cao_generate_username_button.setGeometry(QRect(435, 90, 25, 25))
        self.cao_generate_username_button.setLayoutDirection(Qt.LeftToRight)
        self.cao_generate_username_button.setStyleSheet(u"#createDataRUNGBtn {\n"
"	border: none;\n"
"}")
        self.cao_generate_username_button.setLocale(QLocale(QLocale.English, QLocale.Canada))
        self.cao_generate_username_button.setIcon(icon)
        self.eto_group_box = QGroupBox(self.central_widget)
        self.eto_group_box.setObjectName(u"eto_group_box")
        self.eto_group_box.setGeometry(QRect(270, 50, 480, 270))
        self.eto_cancel_button = QPushButton(self.eto_group_box)
        self.eto_cancel_button.setObjectName(u"eto_cancel_button")
        self.eto_cancel_button.setGeometry(QRect(20, 230, 100, 25))
        self.eto_password_line_edit = QLineEdit(self.eto_group_box)
        self.eto_password_line_edit.setObjectName(u"eto_password_line_edit")
        self.eto_password_line_edit.setGeometry(QRect(155, 130, 270, 25))
        self.eto_update_button = QPushButton(self.eto_group_box)
        self.eto_update_button.setObjectName(u"eto_update_button")
        self.eto_update_button.setGeometry(QRect(170, 230, 100, 25))
        self.eto_object_name_label = QLabel(self.eto_group_box)
        self.eto_object_name_label.setObjectName(u"eto_object_name_label")
        self.eto_object_name_label.setGeometry(QRect(20, 50, 100, 25))
        self.eto_object_name_line_edit = QLineEdit(self.eto_group_box)
        self.eto_object_name_line_edit.setObjectName(u"eto_object_name_line_edit")
        self.eto_object_name_line_edit.setGeometry(QRect(155, 50, 270, 25))
        self.eto_username_label = QLabel(self.eto_group_box)
        self.eto_username_label.setObjectName(u"eto_username_label")
        self.eto_username_label.setGeometry(QRect(20, 90, 100, 25))
        self.eto_url_label = QLabel(self.eto_group_box)
        self.eto_url_label.setObjectName(u"eto_url_label")
        self.eto_url_label.setGeometry(QRect(20, 170, 100, 25))
        self.eto_username_line_edit = QLineEdit(self.eto_group_box)
        self.eto_username_line_edit.setObjectName(u"eto_username_line_edit")
        self.eto_username_line_edit.setGeometry(QRect(155, 90, 270, 25))
        self.eto_password_label = QLabel(self.eto_group_box)
        self.eto_password_label.setObjectName(u"eto_password_label")
        self.eto_password_label.setGeometry(QRect(20, 130, 100, 25))
        self.eto_url_line_edit = QLineEdit(self.eto_group_box)
        self.eto_url_line_edit.setObjectName(u"eto_url_line_edit")
        self.eto_url_line_edit.setGeometry(QRect(155, 170, 270, 25))
        self.eto_generate_password_button = QPushButton(self.eto_group_box)
        self.eto_generate_password_button.setObjectName(u"eto_generate_password_button")
        self.eto_generate_password_button.setGeometry(QRect(435, 130, 25, 25))
        self.eto_generate_password_button.setStyleSheet(u"#editDataRPGBtn {\n"
"	border: none;\n"
"}")
        self.eto_generate_password_button.setIcon(icon)
        self.eto_generate_username_button = QPushButton(self.eto_group_box)
        self.eto_generate_username_button.setObjectName(u"eto_generate_username_button")
        self.eto_generate_username_button.setEnabled(True)
        self.eto_generate_username_button.setGeometry(QRect(435, 90, 25, 25))
        self.eto_generate_username_button.setAutoFillBackground(False)
        self.eto_generate_username_button.setStyleSheet(u"#editDataRUNGBtn {\n"
"	border: none;\n"
"}")
        self.eto_generate_username_button.setIcon(icon)
        self.eto_generate_username_button.setCheckable(False)
        self.logo_label = QLabel(self.central_widget)
        self.logo_label.setObjectName(u"logo_label")
        self.logo_label.setGeometry(QRect(15, 10, 30, 30))
        self.logo_label.setPixmap(QPixmap(u":/logos/password_king_logo.png"))
        self.logo_label.setScaledContents(True)
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QMenuBar(MainWindow)
        self.menu_bar.setObjectName(u"menu_bar")
        self.menu_bar.setGeometry(QRect(0, 0, 760, 22))
        self.help_menu = QMenu(self.menu_bar)
        self.help_menu.setObjectName(u"help_menu")
        MainWindow.setMenuBar(self.menu_bar)

        self.menu_bar.addAction(self.help_menu.menuAction())
        self.help_menu.addAction(self.help_page_action)
        self.help_menu.addAction(self.credits_action)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Password King Manager", None))
        self.actionPassword_Manager.setText(QCoreApplication.translate("MainWindow", u"Password Manager", None))
        self.actionPassword_Generator.setText(QCoreApplication.translate("MainWindow", u"Password Generator", None))
        self.actionUser_Name_Generator.setText(QCoreApplication.translate("MainWindow", u"User Name Generator", None))
        self.import_action.setText(QCoreApplication.translate("MainWindow", u"Import Passwords", None))
        self.export_action.setText(QCoreApplication.translate("MainWindow", u"Export Passwords", None))
        self.credits_action.setText(QCoreApplication.translate("MainWindow", u"Credits", None))
        self.help_page_action.setText(QCoreApplication.translate("MainWindow", u"Help page", None))
        self.header_1_label.setText(QCoreApplication.translate("MainWindow", u"Password King Password Manager", None))
        self.cao_group_box.setTitle(QCoreApplication.translate("MainWindow", u"Create an Object", None))
        self.cao_cancel_button.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.cao_password_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your password", None))
        self.cao_add_button.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.cao_object_name_label.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.cao_object_name_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter the object name", None))
        self.cao_username_label.setText(QCoreApplication.translate("MainWindow", u"User Name", None))
        self.cao_url_label.setText(QCoreApplication.translate("MainWindow", u"URL", None))
        self.cao_username_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your username", None))
        self.cao_password_label.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.cao_url_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter the url", None))
        self.cao_generate_password_button.setText("")
        self.cao_generate_username_button.setText("")
        self.eto_group_box.setTitle(QCoreApplication.translate("MainWindow", u"Edit The Object", None))
        self.eto_cancel_button.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.eto_password_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your password", None))
        self.eto_update_button.setText(QCoreApplication.translate("MainWindow", u"Update", None))
        self.eto_object_name_label.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.eto_object_name_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter the object name", None))
        self.eto_username_label.setText(QCoreApplication.translate("MainWindow", u"User Name", None))
        self.eto_url_label.setText(QCoreApplication.translate("MainWindow", u"URL", None))
        self.eto_username_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your user name", None))
        self.eto_password_label.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.eto_url_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter the url", None))
        self.eto_generate_password_button.setText("")
        self.eto_generate_username_button.setText("")
        self.logo_label.setText("")
        self.help_menu.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

